dist: xenial

language: python

branches:
  only:
    - master

matrix:
  include:
    - stage: Tests (Python 2.7)
      python: 2.7
      env: TOXENV=py27,pylint

    - stage: Tests (Python 3.8)
      python: 3.8
      env: TOXENV=py27,flake8,pylint

install:
  - pip install tox

script:
  - tox